name: Node

on:
  pull_request:
  push:
    branches:
      - master
      - stable*

jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [11.x]

    steps:
      - uses: actions/checkout@v2
      - name: Use node ${{ matrix.node-version }}
        uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node-version }}
      - name: Install dependencies & build
        run: |
          npm ci
          npm run build --if-present

  lint:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [11.x]

    steps:
      - uses: actions/checkout@v2
      - name: Use node ${{ matrix.node-version }}
        uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node-version }}
      - name: Install dependencies
        run: npm ci
      - name: ESLint
        run: npm run lint
      - name: Stylelint
        run: npm run stylelint
